version: "3.9"

services:
  app:
    build: .
    image: video_platform-app:latest
    container_name: video-platform-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - /home/shabri/apps/platform-video/video-storage:/app/video-storage # bind mount
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: video-platform-db
    environment:
      POSTGRES_DB: video_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1122
    ports:
      - "5432:5432"
    volumes:
      - /home/shabri/apps/platform-video/postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
